### ISSUE TITLE
Error, export not found, but I created it yesterday and saw it run

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#125]
I created a "private" export job that now I do not seem to be able to find again.

And I am not clear on what private means, just not in list and search results, or can't access at all, even with the direct link.

http://export.hotosm.org/en/exports/e3d9bb76-24b1-406f-9989-84e79e6d8fd3/

**Comment by bdon** [comment]
In this case "Private" means unpublished. There is a scheduled job that deletes unpublished jobs from the database after 48 hours, so there is no record of the export you created on May 16, 2016. 

It does seem strange that it was deleted seemingly less than 48 hours after you created it. However, on the live Exports site, there are unpublished jobs up to 2 days old, so it's possible that in the past there was a bug related to the timing of the deletion that has since been fixed.

**Comment by bdon** [comment]
via @PaulUithol we should evaluate how the "published" checkbox works. Checked by default? It would also be helpful for debugging if rows were never deleted from the DB.

**Comment by mataharimhairi** [comment]
I think the idea was to have unpublished exports deleted after a certain amount of time to reduce clutter and minimise the use of database storage. 48 hours may be a little too short though, and I would definitely think that checking the 'published' checkbox by default would be safer since not everyone will understand how the saving system works. Perhaps unpublished exports should be deleted automatically after a longer time period (2 months), or is it necessary at all?

**Comment by bdon** [comment]
@PaulUithol there was a formatting issue in my reply on the previous thread - I meant to say that "unpublished" exports are publicly accessible via http://export.hotosm.org/en/exports/EXPORT_UID . They do not however appear in the public list at http://export.hotosm.org/en/exports .

**Comment by bdon** [comment]
I just had one of my own exports disappear out from under me. I suspect it may also have to do with the "is_staff" property. 

For now, why don't we just keep all exports regardless of private/public? We're not limited on space right now, and can re-evaluate storage needs when we move to a different production environment. @mataharimhairi

**Comment by bdon** [comment]
Disabled the scheduled job for now. Will revisit purging expired jobs when we implement the scheduler for automated periodic exports.
