### ISSUE TITLE
Purge expired jobs

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#140]
Just adding this in as a reminder:

'Disabled scheduled jobs for now. Will revisit purging expired jobs when we implement the scheduler for automated periodic exports.' - Brandon Liu

**Comment by mojodna** [comment]
Make sure that HDX downloads shouldn't be deleted. (Denormalize `jobs` table to include flag re: whether it's an HDX job?)

Reconsider renaming download / staging directories re: whether they should be based on the job or the run.

**Comment by mojodna** [comment]
eab52279d33418eec01256688fc6d7985c526828 disabled them.

**Comment by mojodna** [comment]
Revisiting this, the previous implementation was purging **private** ("unpublished") exports after 48 hours. There's definitely convenience in keeping them around since individuals may be sharing them with broader groups even if the export itself isn't public.

I did some cleanup in the process (ensuring that the `staging` directory gets cleared up when an export finishes), but I'm going to leave private jobs available indefinitely.
