### ISSUE TITLE
Handle Regions Crossing International Date Line (Fiji) ?

### ISSUE THREAD

**Issue by bdon** [hotosm/osm-export-tool2#145]

**Comment by bdon** [comment]
I suggest that:
1) the frontend drawing tool should crop any bounds to the 180th meridian. This means an area crossing can be selected as two different areas.
2) the backend should not accept any areas crossing the 180th meridian.

**Comment by mataharimhairi** [comment]
A work around is to have a pop up box notifying users trying to select an area that crosses the international date line, that they will have to create the export in two parts @bdon

**Comment by bdon** [comment]
This was pretty sophisticated to solve.

1) the interactive map when drawing no longer wraps at the antimeridian. This way it is clear which half of the region is selected. Affects part of Fiji.
2) The overpass query MUST limit its bounds to -180 to 180 lon, -90 to 90 lat. Previously this would fail for valid areas in the "Wrapped" portion of the map. this is handled in code now.
3) added additional logging for error case Overpass responses.

**Comment by bdon** [comment]
Updated on exports-prod: https://exports-prod.hotosm.org/en/v3/exports/806940ae-da0f-4fdf-a36f-be8a73ba34b7

**Comment by mataharimhairi** [comment]
The map used in the Export Tool to select the area of interest makes it difficult for users to see the cut off point, due to the trailing gray space on either side. Is there a way to end the map where the cut off is, so users can't scroll further or add a line down the map?

<img width="640" alt="screen shot 2017-08-24 at 18 40 40" src="https://user-images.githubusercontent.com/8972913/29696175-f27c2dc8-88fb-11e7-9ff6-2673b7c11615.png">

VS.

<img width="640" alt="screen shot 2017-08-24 at 18 40 40" src="https://user-images.githubusercontent.com/8972913/29696222-57594442-88fc-11e7-99cd-95eda3ce9669.png">

**Comment by bdon** [comment]
Yes, this is what the cut off looks like now: 

<img width="395" alt="screen shot 2017-09-10 at 7 26 37 pm" src="https://user-images.githubusercontent.com/77501/30253964-13389d52-965e-11e7-893f-c68f086d8678.png">
