### ISSUE TITLE
Link through to TM and OSM Analytics

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#166]
Link through from the Export Tool to the Tasking Manager and OSM Analytics. Something like: 'if you would like to contribute data to this region use the Tasking Manager, or would you like to see data changes over time, use OSM Analytics'.

Love what you guys @mojodna and @bdon did for HDX. So it will be easy for OSM Analytics to use the same area supplied to the Export Tool, but it might have to be a generic link to the Tasking Manager? 

Unless you can think of some way to link to existing projects with similar AOI's, so that users don't have to search or projects with the same region are duplicated.

**Comment by bdon** [comment]
We could have a link through to OSMA on the "Export Detail" page. The same way we link to OSMA from HDX dataset pages.

I'm not sure how the Tasking Manager part would work - wouldn't it only be relevant if an existing Tasking Manager project overlaps with the specified export area?

Otherwise, we can have a link to other HOT resources (like the Tasking Manager) on the landing or about pages

**Comment by bdon** [comment]
Added OSMA link to detail page. TM link can go on the login page with HDX info.
