### ISSUE TITLE
Default Country Option to Selected Area of Interest

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#173]
I accidentally forgot to change the country from 'Singapore' to 'Indonesia' when I was creating a test export for Bali. Is there a way for the tool to detect the right country to use based on the export area selected?

<img width="1262" alt="screen shot 2017-05-04 at 22 09 18" src="https://cloud.githubusercontent.com/assets/8972913/25739225/93f4f0f4-31b3-11e7-897f-87c7075cbe2c.png">

**Comment by mojodna** [comment]
Not really. We'd need to essentially do a polygon intersection query (with something, not sure what would be appropriate and easily available) every time the AOI changes and see what countries it overlaps. I'm not sure where I'd start to do this.

**Comment by mataharimhairi** [comment]
Not to worry. Its not really a priority at this point. Just thought it would be a nice feature to help reduce human error. Looks like the data team will just have to be more careful than I was :)

**Comment by bdon** [comment]
I think the entry of country codes should always be done manually.

1) an area that slightly overlaps multiple countries, but is focused on a crisis region in one country, would likely only want to have one country tag.
2) anything that tries to automate this would need to depend on a set of admin0 polygons which don't necessarily encode disputed territories e.g. Western Sahara. We'd want to make sure the data team is explicit about what countries are tagged because the choice of country for a given AOI could be politically sensitive.

Please re-open if you have another idea of how this would be implemented
