### ISSUE TITLE
Option to Manually Enter 'Buffer AOI' Distance

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#203]
Is there are way to easily implement the option to manually override the default buffer distance?

**Comment by bdon** [comment]
I think if this was exposed to the user it would be difficult to understand - the buffering area is only really for large regions, and the units are degrees which don't map consistently to kilometers. I think users that need more specific areas should be able to buffer any geometries in their own GIS program or otherwise draw an extent using the freeform tool.

In the case where simplification happens that potentially loses area - I'm investigating if the simplification can be improved

**Comment by mataharimhairi** [comment]
That sounds like a good alternative. If the amount of simplification can be reduced, that might help with the loss of features close to the boundary. At the moment, the boundary is automatically altered too much.

**Comment by bdon** [comment]
@mataharimhairi can you try creating a Surabaya export again on staging and see if the simplification has improved?

**Comment by bdon** [comment]
@mataharimhairi can you check that the GeoJSON that was oversimplified before is fine now? Closing this issue.
