### ISSUE TITLE
Is Load From JOSM Preset Working?

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#205]
I tried loading an Indonesian Preset in the YAML option on the '3. Feature Selection' tab (staging) with no luck. Wasn't sure if it was going to show the transformation from Preset --> YAML in the window, so I just hit 'Next' and 'Create Export'. Turns out that only buildings were extracted, as this is the default text in the YAML window.

**Comment by bdon** [comment]
@mataharimhairi can you link the Josm preset XML? and what browser were you using?

**Comment by mataharimhairi** [comment]
I was using Chrome. Here is the link to the preset: https://goo.gl/26rD3t

**Comment by bdon** [comment]
The JOSM Preset parser is failing because of entities in the XML like this:

    <item name="-----------------------------------">
    </item>

    <item name="======PRESETS OSM INDONESIA ======">
			<label text="Berikut ini adalah preset untuk pemetaan openstreetmap di Indonesia"/>
		</item>

I don't think these are valid JOSM presets, because each item element must have a "type" attribute. Looks like those item elements were inserted for formatting. Taking those Item elements out makes the preset parser work fine. @mataharimhairi can you check if your other presets have similar issues? If so I'll add an error message or work around this particular case.

**Comment by bdon** [comment]
Resolved by skipping invalid Item elements
