### ISSUE TITLE
Test Maps.me Export 

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#247]

**Comment by mojodna** [comment]
It works on Android.

I downloaded the zip file locally, unzipped it, and served up the MWM file so that I could download it from my Android phone (email would also work). Once I had it on the phone, I moved it to "Phone storage" > "MapsWithMe" > "170817" (which was the folder that was creating when I downloaded an official map before deleting it) using File Manager.

People who are familiar with this may know better ways to do this; I'd be hesitant to write up my experience because it's probably somewhat wrong. The upshot is that the MWMs _do_ work!

**Comment by mataharimhairi** [comment]
@mojodna I would add it to the learn section anyways, as it provides users with a starting point and hopefully we will get feedback about an easier way to do it, if its exists. It's a great way to improve! Thanks for testing :)

**Comment by mojodna** [comment]
Documented in e9d43ca
