### ISSUE TITLE
Job Fail - Works When Only Selecting SHP + GPKG

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#248]
FAILED (All File Formats) https://exports-staging.hotosm.org/en/v3/exports/769f7d4c-f56d-41b6-8c8d-2fec0156adac

SUCEEDED (Shp + Gpkg) https://exports-staging.hotosm.org/en/v3/exports/cdf967ee-badc-4767-b083-b8b81268041e

**Comment by mojodna** [comment]
https://sentry.io/humanitarian-openstreetmap-tea/export-tool-2-staging/issues/347520899/

**Comment by mojodna** [comment]
Proximate cause: Garmin IMG format

**Comment by mojodna** [comment]
OBF is also problematic with this same region: https://sentry.io/humanitarian-openstreetmap-tea/export-tool-2-staging/issues/341793431/

**Comment by bdon** [comment]
DEBUG:utils.garmin_img:Running: java -Xmx1024m -jar ../splitter-r583/splitter.jar --polygon-file=scratch//bounds.poly --output-dir=scratch/ scratch/export.pbf
Splitter version 583 compiled 2017-04-01T15:52:04+0100
boundary-tags=use-exclude-list
cache=
description=
geonames-file=
handle-element-version=remove
ignore-osm-bounds=false
keep-complete=true
mapid=63240001
max-areas=2048
max-nodes=1600000
max-threads=4 (auto)
mixed=false
no-trim=false
num-tiles=
output=pbf
output-dir=scratch/
overlap=auto
polygon-desc-file=
polygon-file=scratch//bounds.poly
precomp-sea=
problem-file=
problem-report=
resolution=13
search-limit=200000
split-file=
status-freq=120
stop-after=dist
wanted-admin-level=5
write-kml=
Elapsed time: 0s   Memory: Current 245MB (5MB used, 240MB free) Max 910MB
Time started: Wed Sep 13 13:23:13 EDT 2017
Warning: Bounding polygon is complex. Splitter might not be able to fit all tiles into the polygon!
Map is being split for resolution 13:
 - area boundaries are aligned to 0x800 map units (0.0439453125 degrees)
 - areas are multiples of 0x800 map units wide and high
Processing scratch/export.pbf
Fill-densities-map pass took 2709 ms
Exact map coverage read from input file(s) is (16.68250322341919,-73.70182514190674) to (21.962056159973145,-61.67179584503174)
Exact map coverage after applying bounding box of polygon-file is (16.68250322341919,-73.70182514190674) to (21.962056159973145,-61.67179584503174)
Rounded map coverage is (16.6552734375,-73.740234375) to (21.97265625,-61.6552734375)
Splitting nodes into areas containing a maximum of 1,600,000 nodes each...
splitting export_bounds
Highest node count in a single grid element is 61,118
Highest node count in a single grid element within the bounding polygon is 61,118
Warning: shape is too complex, using rectangle (16.6552734375,-73.740234375) to (21.97265625,-61.6552734375) with 1,074,270 nodes instead
Trying to find nice split for (16.6552734375,-73.740234375) to (21.97265625,-61.6552734375) with 1,074,270 nodes
searching for split with min-nodes 80000, learned 0 good partial solutions
searching for split with min-nodes 80000, learned 0 good partial solutions
No good solution found, trying to find one accepting anything
max-nodes value 1600000 is far above highest node count 61118 in single grid element, consider using a lower resolution.
searching for split with min-nodes 1, learned 0 good partial solutions
Still no good solution found, trying alternate algorithm
searching for split with min-nodes 16000, learned 0 good partial solutions
No good solution found, trying to find one accepting anything
max-nodes value 1600000 is far above highest node count 61118 in single grid element, consider using a lower resolution.
searching for split with min-nodes 1, learned 0 good partial solutions
Trying to cut the areas so that they fit into the polygon ...
Failed to calculate areas. See stdout messages for details.
Failed to calculate areas.
Sorry. Cannot split the file without creating huge, almost empty, tiles.
Please specify a bounding polygon with the --polygon-file parameter.
Traceback (most recent call last):
  File "utils/manager.py", line 223, in <module>
    r.run()
  File "utils/manager.py", line 187, in run
    self.run_format(formatcls)
  File "utils/manager.py", line 181, in run_format
    task.run()
  File "/Users/Bdon/workspace/hot/osm-export-tool2/utils/garmin_img.py", line 54, in run
    subprocess.check_call(cmd, shell=True, executable='/bin/bash')
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'java -Xmx1024m -jar ../splitter-r583/splitter.jar --polygon-file=scratch//bounds.poly --output-dir=scratch/ scratch/export.pbf' returned non-zero exit status 1

**Comment by bdon** [comment]
This should be resolved by query speedup + changing limits and changes to the IMG filtering process.
