### ISSUE TITLE
List creator of export on the export info page

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#28]
It would be helpful to see who created an export so I could contact them if need be. For example, if I see someone already created an export for a village or district I wanted to create an export for, I might really like to contact the creator and see what project they or activity they were involved in as maybe we have room for exchange or collaboration.

**Comment by bjohare** [comment]
Added this. Also added it to a tooltip on the export list page and added filtering by username to search form.

**Comment by mataharimhairi** [comment]
Tried it out. Went to the Exports page and found that it is not added to the table as an additional column, but only appears when you hover over the Export. 

I think it would be best added at the end of the table in a column so that everyone can see it. I know it is in the tooltips, but many people do not read this and only go based on what they can see. 

If space is an issue, you can try reducing the date and time the export is created to simply the date. I don't think we need to keep a record of the exact time. I tried searching for usernames with the text box and this worked perfectly.

**Comment by mataharimhairi** [comment]
A 'Owner' column has been added at the end of the 'Exports' table, which allows users to instantly see who originally created it.
