### ISSUE TITLE
Select from either the HDM or OSM data models

### ISSUE THREAD

**Issue by severinmenard** [hotosm/osm-export-tool2#53]
Maybe easier if not having to untick first the default tree to select the other one. Ticking the other one making automatically the first one would be possible ?

**Comment by mataharimhairi** [comment]
I believe it would be more upsetting to a user if they were to lose their individual selections made on the first tree (i.e. HDM) by trying to select some on the other tree (i.e. OSM), rather than realising that they have to untick the original one first. It almost acts as a safety measure, so that the user won't lose everything by accident and have to start over again.
