### ISSUE TITLE
Does feature selection filter tags and geometries?

### ISSUE THREAD

**Issue by severinmenard** [hotosm/osm-export-tool2#59]
Is it only a tag filter or also a geometry filter? Seems so, bu eg I created this job http://hot.geoweb.io/fr/exports/11625c6b-3eb2-4c2e-b800-2b7fa79c6d0b/ with only the transportation tag scheme, but the shp attribute tables, either with the generic OSM or with the HDM tag schemes, shows objects without any tag except building=yes what prevents to understand how they are supposed to be part of the transportation scheme. Missing an extra tag or missing in the transportation scheme?

**Comment by bjohare** [comment]
I see the building=yes in planet_osm_point and planet_osm_polygon tables.. not sure what's happening there as they should not be included. Needs more investigation.

**Comment by mataharimhairi** [comment]
I tried to replicate this issue with the following export as the one that you created @severinmenard no longer exists:

http://export.hotosm.org/en/exports/c8abd4fa-e865-4db4-8ef2-8bf9de4f44be/

It seems as though the building tags are no longer being exported. Was this fixed in a release @bjohare or is it still happening elsewhere?

**Comment by bdon** [comment]
This should be resolved with the new YAML tag definition and the replacement of the "Thematic Shapefile" format, as well as the reimplementation of the tree tag filters.
