### ISSUE TITLE
Review HDM and OSM Data Models for completeness

### ISSUE THREAD

**Issue by bjohare** [hotosm/osm-export-tool2#79]
The [HDM](https://github.com/hotosm/osm-export-tool2/tree/master/api/presets/hdm_presets.xml) and [OSM](https://github.com/hotosm/osm-export-tool2/blob/master/api/presets/osm_presets.xml) data models should be reivewed for completeness and updated if necessary.

**Comment by PaulUithol** [comment]
I'm not entirely clear on what the exact difference between the HDM and OSM sets of data should be - could you fill me in on that a bit? I know there's things like `hazard_prone`, but apart from that I'm having a hard time finding the differences. Couldn't they share a common base file for example, making it easier to compare?

As an aside, I've also wondered why I wouldn't be able to simple paste a list of comma/semicolon separated tags somewhere, and get those exported. Seems a lot simpler for the average user than crafting a preset file?

**Comment by d3netxer** [comment]
I think that the HDM should include every tag in the OSM Data model. Maybe this is already the case. I would like to know currently if I select the main checkbox for the HDM if I am 'missing' any standard OSM features from the OSM data model. This is important to document.

**Comment by PaulUithol** [comment]
So do I; hence my suggestion to use a common base file? It would also make tag selection much easier to understand if you could select the OSM model, and additionally export the HDM-specific tags as well. At the moment, they look like to totally separate trees, which they're not.

**Comment by mataharimhairi** [comment]
On reflection and actual use of the Export Tool the field, I have to agree that having both the HDM and OSM Data Model in the 'Tree Tag' tab is kind of redundant and confusing. It actually makes more sense to have all the map features available for selection under just the OSM Data Model. This way they are not duplicated and confusing for the user as to 'what's the difference?'. This combined with the enhancement of a 'text box' to search for tags in the tree would be great.

Then the HDM preset (once reviewed by the Activation WG) can be offered as an option on the 'Preset File' tab, as an extra button at the bottom of the tab between the 'Upload Preset' and 'Select Stored Preset'. The HDM Data Model is meant to contain all the map features deemed necessary for humanitarian response. However each case varies, which is why it is important the the data model be reviewed by the Activation WG. We want to make sure we aren't missing any vital ones, yet at the same time don't want to overload it.

@bjohare Would this take a lot from your side to implement? I can assist you were possible in 3 weeks time and of course do up the help documentation to reflect the changes!

**Comment by mataharimhairi** [comment]
https://github.com/hotosm/osm-export-tool2/issues/78

**Comment by skorasaurus** [comment]
@bjohare Where did you obtain the hdm.xml from? It looks quite different than what's at https://github.com/hotosm/presets/blob/master/HDM.xml

**Comment by bjohare** [comment]
@skorasaurus it's from the url you posted above, but with modifications. There were omissions in highways and landuse in particular.

**Comment by JivanAmara** [comment]
Do I understand correctly that the hdm is a convenient subset of the osm fields for humanitarian use?

**Comment by mojodna** [comment]
Yup, see https://wiki.openstreetmap.org/wiki/Humanitarian_OSM_Tags for more info.

**Comment by PaulUithol** [comment]
Per request from @bdon, docs to cross ref:

- data model for Indonesia: https://docs.google.com/document/d/1ivWj7AfMT4W4m8uymhBLmr7ZQ6YkoaiaqBYODkmrwIk/
- Ramani Huria/Tanzania: https://docs.google.com/document/d/1KaQNZGoXlAQhhYUPXy1EehbqP9ds0ZV9r5andoTVgtc/
- proposed Maps.me categories: https://docs.google.com/document/d/1RnOT0fKRtZ3HTsyB2CZAKtTokTykJwhzwJp_kPqQhrk/
- Healthsites: https://github.com/hotosm/health/wiki/Health-facility-tagging-within-OSM-(proposal)
- WaSH: incomplete. https://wiki.openstreetmap.org/wiki/Humanitarian_OSM_Tags/WASH
- Refugee situations:
  - UNHCR presets: https://github.com/unhcr/presets
  - As used in Jordan, Greece, France for refugees: https://pad.hackerspace.gr/p/Refugee_camp_tagging

**Comment by bdon** [comment]
Example for Indonesia `finance` layer:

```
finance:
  select:
    - amenity
    - building
    - name
    - addr:full
    - capacity
    - building:levels
    - building:structure
    - building:walls
    - building:floor
    - building:roof
    - access:roof
    - building:condition
    - backup_generator
  where: amenity = 'bank' OR building = 'bank'
```

From the data model, it seems like this filtering of banks (amenity OR building is tagged bank) makes sense, this would need to be written by hand based on the tag specification

**Comment by bdon** [comment]
Tag tree should have "Other" or "*" categories for all features within a category
Tooltips for more information on each checkbox

**Comment by bdon** [comment]
@mataharimhairi reading over your last email, I realized that maybe a simpler design for the Tag Tree is:

Rather than have the Parent Checkbox for an entire category like Financial select all the checkboxes under it, it should instead be defined as its own selection, possibly including more tags than all the individual checkboxes. This would avoid having to add an "Other" child checkbox in each category.

**Comment by mataharimhairi** [comment]
This is exactly the set up I had envisioned. Thanks @bdon!
