### ISSUE TITLE
Transifex Setup

### ISSUE THREAD

**Issue by arushivashist** [hotosm/osm-export-tool2#8]
When the UI of the Export Tool will be finalized, the documentation will be translated into five languages: 
 Bahasa Indoneisa, Deustch, Espanol, Francis and Japanese using Transifex.

**Comment by mataharimhairi** [comment]
The project has now been set up in Transifex to be translated into 34 languages:

https://www.transifex.com/hotosm/osm-export-tool2/

Once all the naming conventions are settled on and the final help documentation review is done, we will request assistance from the HOT Indonesian team to do some preliminary testing.

**Comment by mataharimhairi** [comment]
The new Export Tool site has been hooked up to Transifex for translation [1]. I will request assistance from the HOT Indonesian team to translate this week after the final revision of the help documentation is complete, so that we can test it before it goes live on the 28th September.

[1] https://www.transifex.com/hotosm/osm-export-tool2/
