### ISSUE TITLE
Overlapping polygons are badly exported

### ISSUE THREAD

**Issue by severinmenard** [hotosm/osm-export-tool2#97]
Look at the is export: 
![selection_026](https://cloud.githubusercontent.com/assets/1291055/10559682/7922e7a8-74e6-11e5-960d-2ea7ed4d6ca6.png)

you can see that the dark grey polygon on the left is cut by the export window.

Here is what it looks like when loaded in QGIS:

![selection_027](https://cloud.githubusercontent.com/assets/1291055/10559690/9d485c80-74e6-11e5-871c-5c54c04daa35.png)

So the object remains but not all its nodes, what leads to an incomplete shape. It should either work as in JOSM (the entire object is downloaded) or ignore objects not completely inside the download area.

**Comment by mataharimhairi** [comment]
I tried to replicate the issue above with the following export covering the same area:

http://export.hotosm.org/en/exports/8c412201-e002-453a-8031-1836d63aaed5/

Looks like this has been fixed. It wasn't specified if the problem was with the OSM or Thematic Schema shapefiles, so I tested both with the same results in QGIS:

<img width="683" alt="screen shot 2016-01-19 at 20 40 27" src="https://cloud.githubusercontent.com/assets/8972913/12427033/ef36ad48-beed-11e5-819a-c3b08615fca9.png">

**Comment by mojodna** [comment]
https://github.com/AmericanRedCross/osm-export-tool2/commit/c12405d596144fd79da988b381acf7c1b9b087f6 may fix this issue, as it ensures that all entities referred to in a way or relation are included.

Then again, the problem could also be in the shapefile conversion.

**Comment by bdon** [comment]
This has been resolved to include entire polygons bordering the extent. Screenshot of new output (green) for the area @severinmenard requested, compared to previous (pink):

<img width="541" alt="screen shot 2017-03-10 at 10 20 43 am" src="https://cloud.githubusercontent.com/assets/77501/23801095/daff9a8e-057c-11e7-95ba-7d9bda041252.png">
